//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NqmLeson11K22cntt1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NqmTaiKhoan
    {
        public int NqmId { get; set; }
        public string NqmUseName { get; set; }
        public string NqmPassword { get; set; }
        public string NqmFullName { get; set; }
        public Nullable<int> NqmAge { get; set; }
        public string NqmEmail { get; set; }
        public string NqmPhone { get; set; }
        public string NqmStatus { get; set; }
    }
}
